name: Build and Deploy Docker Compose Application
 
on:
push:
   branches:
     - main
 
jobs:
build-and-deploy:
   runs-on: ubuntu-latest
 
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
 
   - name: Set up Docker Buildx
     uses: docker/setup-qemu-action@v1
 
   - name: Login to DockerHub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
 
   - name: Build and push Docker images
     uses: docker/build-push-action@v2
     with:
       context: .
       push: true
       tags: your-dockerhub-username/your-repo-name:latest
 
   - name: Run Docker Compose
     run: |
       docker-compose up -d
